n1 = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(n1))
print(f'Só tem números? {n1.isnumeric()}')
print(f'Só tem letras? {n1.isalpha()}')
print(f'Tem letras e números? {n1.isalnum()}')
print(f'Está em maiúsculas? {n1.isupper()}')
print(f'Está em letras minusculas? {n1.islower()}')
print(f'Está capitalizada? {n1.istitle()}')
